language: python
python:
    - "3.6"
    - "3.7"
install:
    - "pip install -q -e ."
    - "pip install coverage"
    - "pip install coveralls"
script:
    - "coverage run --source=pygazebo setup.py test"
after_success:
    coveralls
